//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtransfertBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public string Id { get; set; }
        public string Nom { get; set; }
        public string Numero { get; set; }
        public string Utilisateur { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
