//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtransfertBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListeTransfert
    {
        public string Id { get; set; }
        public string IdTransaction { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public string Email { get; set; }
        public double SeuilUnite { get; set; }
        public double CompteUnite { get; set; }
        public string Numero { get; set; }
        public double Montant { get; set; }
        public double Pourcentage { get; set; }
        public double Total { get; set; }
        public string TypeTransaction { get; set; }
        public string TypeTransfert { get; set; }
        public string message { get; set; }
        public string Utilisateur { get; set; }
        public string status { get; set; }
    }
}
