//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtransfertBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTransferttestEntities : DbContext
    {
        public eTransferttestEntities()
            : base("name=eTransferttestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Comptes> Comptes { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<RechargeCptePrincTrace> RechargeCptePrincTrace { get; set; }
        public virtual DbSet<TodoItems> TodoItems { get; set; }
        public virtual DbSet<Trace> Trace { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<ListeTransactions> ListeTransactions { get; set; }
        public virtual DbSet<ListeTransfert> ListeTransfert { get; set; }
        public virtual DbSet<ListeTransactionsFull> ListeTransactionsFull { get; set; }
    }
}
