//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtransfertBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trace
    {
        public string Id { get; set; }
        public System.DateTime DateTransaction { get; set; }
        public double Montant { get; set; }
        public string Receiveremail { get; set; }
        public string Senderemail { get; set; }
        public string TypeTransaction { get; set; }
    }
}
