//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtransfertBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public string Etat { get; set; }
        public string Liste { get; set; }
        public double Montant { get; set; }
        public string Numero { get; set; }
        public double Pourcentage { get; set; }
        public double Total { get; set; }
        public string TypeTransaction { get; set; }
        public string TypeTransfert { get; set; }
        public string htmlMessage { get; set; }
        public string Utilisateur { get; set; }
        public string message { get; set; }
        public string numerotransaction { get; set; }
        public string reponse { get; set; }
        public string status { get; set; }
        public string ModePaiement { get; set; }
        public string buyer_name { get; set; }
        public string log { get; set; }
        public string statuscinetpay { get; set; }
        public string statustransfert { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
